{
 "title": "S.M.A.R.T. 현황",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "전체 서버 HDD 장애 예측 현황",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ampm_smart_failure_proba{model=\"BestEstimator\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "민지 서버 HDD 장애 예측 현황",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ampm_smart_failure_proba{exported_instance=\"minji-server:8001\",model=\"BestEstimator\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "지현 서버 HDD 장애 예측 현황",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "ampm_smart_failure_proba{exported_instance=\"jihyun-server:9103\",model=\"BestEstimator\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "인예 서버 HDD 장애 예측 현황",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "ampm_smart_failure_proba{exported_instance=\"inye-server:8002\", model=\"BestEstimator\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "민지 서버 HDD S.M.A.R.T. 현황",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_smart_smart_attribute_current{instance=\"minji-server:8001\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "지현 서버 HDD S.M.A.R.T. 현황",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_smart_smart_attribute_current{instance=\"jihyun-server:9103\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "인예 서버 HDD S.M.A.R.T. 현황",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_smart_smart_attribute_current{instance=\"inye-server:8002\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}