{
 "title": "smart",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "전체 서버 hdd failrue 예측 확률 현황",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ampm_smart_failure_proba{model=\"RandomForestClassifier\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "A 서버 HDD failrue 예측",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ampm_smart_failure{exported_instance=\"test-exporter:8001\"}",
     "legendFormat": "{{drive}}-{{model}}"
    }
   ]
  },
  {
   "title": "A 서버 메모리 현황",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "collectd_memory{instance=\"collectd-exporter:9103\"}",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "A 서버 CPU 현황",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_cpu_total{cpu=\"0\",instance=\"collectd-exporter:9103\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "A 서버 HDD SMART 현황",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_smart_smart_attribute_current{instance=\"baidu-exporter:8000\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}